name: Build iOS Kernel Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install ldid dpkg xz

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Build project
      run: make

    - name: Create .deb package
      run: |
        PACKAGE_NAME="com.example.mykernelextension"
        PACKAGE_VERSION="0.0.1"
        ARCHITECTURE="iphoneos-arm"
        INSTALL_PATH="/Library/MobileSubstrate/DynamicLibraries"

        TEMP_DIR=$(mktemp -d)
        mkdir -p "${TEMP_DIR}${INSTALL_PATH}"
        mkdir -p "${TEMP_DIR}/DEBIAN"

        cp "MyKernelExtension" "${TEMP_DIR}${INSTALL_PATH}/"

        cat << EOF > "${TEMP_DIR}/DEBIAN/control"
        Package: ${PACKAGE_NAME}
        Name: MyKernelExtension
        Version: ${PACKAGE_VERSION}
        Architecture: ${ARCHITECTURE}
        Description: An example iOS kernel extension
        Maintainer: Your Name
        Author: Your Name
        Section: System
        EOF

        dpkg-deb -b "${TEMP_DIR}" "${PACKAGE_NAME}_${PACKAGE_VERSION}_${ARCHITECTURE}.deb"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyKernelExtension
        path: ./*.deb