name: Build iOS Kernel Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y fakeroot git perl clang-10 build-essential
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-10 100
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-10 100

    - name: Set up theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos
        echo "THEOS=$GITHUB_WORKSPACE/theos" >> $GITHUB_ENV
        echo "$GITHUB_WORKSPACE/theos/bin" >> $GITHUB_PATH

    - name: Install SDK
      run: |
        git clone https://github.com/theos/sdks.git $GITHUB_WORKSPACE/sdks
        mv $GITHUB_WORKSPACE/sdks/*.sdk $GITHUB_WORKSPACE/theos/sdks/

    - name: Build Kernel Extension
      run: |
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: PageTableModifier.kext
        path: .theos/obj/debug/PageTableModifier.kext