name: Build iOS Kernel Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        xcodebuild -version
        
    - name: Install dependencies
      run: |
        brew install ldid
        
    - name: Set up theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos
        echo "THEOS=$GITHUB_WORKSPACE/theos" >> $GITHUB_ENV
        echo "$GITHUB_WORKSPACE/theos/bin" >> $GITHUB_PATH

    - name: Install SDK
      run: |
        git clone https://github.com/theos/sdks.git $GITHUB_WORKSPACE/sdks
        mv $GITHUB_WORKSPACE/sdks/*.sdk $GITHUB_WORKSPACE/theos/sdks/

    - name: Build Kernel Extension
      run: |
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: PageTableModifier.dylib
        path: .theos/obj/debug/PageTableModifier.dylib