name: Build iOS Kernel Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        xcodebuild -version
        
    - name: Install dependencies
      run: |
        brew install ldid
        
    - name: Set up Theos (if needed)
      run: |
        git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos
        echo "THEOS=$GITHUB_WORKSPACE/theos" >> $GITHUB_ENV
        echo "$GITHUB_WORKSPACE/theos/bin" >> $GITHUB_PATH

    - name: Build with Xcode
      run: |
        xcodebuild -workspace YourWorkspace.xcworkspace -scheme YourScheme -sdk iphoneos -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: PageTableModifier
        path: build/Release-iphoneos/PageTableModifier.dylib
