name: Build iOS Kernel Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode.app

    - name: Setup SDKROOT
      run: |
        SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)
        echo "SDKROOT=$SDKROOT"
        echo "SDKROOT=$SDKROOT" >> $GITHUB_ENV

    - name: Create build directory
      run: mkdir -p build

    - name: Compile Kernel Extension
      run: |
        cd build

        # 使用 xcrun 编译内核扩展
        xcrun -sdk iphoneos clang -c ../MyKext.c -o MyKext.o -arch arm64 -mios-version-min=14.0 -I${SDKROOT}/usr/include

        # 链接对象文件生成内核扩展
        xcrun -sdk iphoneos clang MyKext.o -o MyKext.kext -arch arm64 -mios-version-min=14.0 -framework Foundation -framework CoreFoundation

    - name: Sign Kernel Extension
      run: |
        # 替换为你的签名证书名称
        sudo codesign -s "iPhone Developer: Your Name (XXXXXXXXXX)" --force build/MyKext.kext

    - name: Upload Kernel Extension
      uses: actions/upload-artifact@v2
      with:
        name: ios-kernel-extension
        path: build/MyKext.kext
