name: Build iOS Kernel Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List directory contents
      run: |
        echo "Listing root directory contents:"
        ls -la

    - name: Setup Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode.app

    - name: Install Dependencies
      run: |
        brew install cmake # 如果需要其他工具或依赖，请在这里安装

    - name: Compile Kernel Extension
      run: |
        # 创建构建目录
        mkdir -p build
        cd build

        # 设置 SDK 路径
        SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)
        export SDKROOT

        # 编译内核扩展
        xcrun -sdk iphoneos clang -c ../MyKext.c -o MyKext.o -arch arm64 -mios-version-min=14.0 -I${SDKROOT}/System/Library/Frameworks/CoreFoundation.framework/Headers

        # 链接对象文件生成内核扩展
        xcrun -sdk iphoneos clang MyKext.o -o MyKext.kext -arch arm64 -mios-version-min=14.0 -framework Foundation -framework CoreFoundation

    - name: Sign Kernel Extension
      run: |
        # 替换为你的签名证书名称
        sudo codesign -s "iPhone Developer: Your Name (XXXXXXXXXX)" --force build/MyKext.kext

    - name: Upload Kernel Extension
      uses: actions/upload-artifact@v2
      with:
        name: ios-kernel-extension
        path: build/MyKext.kext
